name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4

    - name: Copy .env
      run: cp .env.example ./src/.env

    - name: Install Dependencies
      working-directory: ./src
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      working-directory: ./src
      run: php artisan key:generate

    - name: Directory Permissions
      working-directory: ./src
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      working-directory: ./src
      run: |
        mkdir -p database
        touch database/database.sqlite
    
    - name: npm build
      working-directory: ./src
      run: npm run build

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      working-directory: ./src
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test